-- ============================================================
-- ELIMUX SEED DATA - PART 1: COUNTRIES (First 50)
-- Run AFTER 01_schema.sql has been executed
-- ============================================================

INSERT INTO countries (name, iso_code, flag_emoji, currency, is_active) VALUES
('Kenya', 'KE', '🇰🇪', 'KES', true),
('Nigeria', 'NG', '🇳🇬', 'NGN', true),
('South Africa', 'ZA', '🇿🇦', 'ZAR', true),
('Ghana', 'GH', '🇬🇭', 'GHS', true),
('Ethiopia', 'ET', '🇪🇹', 'ETB', true),
('Tanzania', 'TZ', '🇹🇿', 'TZS', true),
('Uganda', 'UG', '🇺🇬', 'UGX', true),
('Rwanda', 'RW', '🇷🇼', 'RWF', true),
('Zambia', 'ZM', '🇿🇲', 'ZMW', true),
('Zimbabwe', 'ZW', '🇿🇼', 'ZWL', true),
('Botswana', 'BW', '🇧🇼', 'BWP', true),
('Namibia', 'NA', '🇳🇦', 'NAD', true),
('Mozambique', 'MZ', '🇲🇿', 'MZN', true),
('Malawi', 'MW', '🇲🇼', 'MWK', true),
('Angola', 'AO', '🇦🇴', 'AOA', true),
('Cameroon', 'CM', '🇨🇲', 'XAF', true),
('Ivory Coast', 'CI', '🇨🇮', 'XOF', true),
('Senegal', 'SN', '🇸🇳', 'XOF', true),
('Morocco', 'MA', '🇲🇦', 'MAD', true),
('Egypt', 'EG', '🇪🇬', 'EGP', true),
('Tunisia', 'TN', '🇹🇳', 'TND', true),
('Algeria', 'DZ', '🇩🇿', 'DZD', true),
('Libya', 'LY', '🇱🇾', 'LYD', true),
('Sudan', 'SD', '🇸🇩', 'SDG', true),
('Democratic Republic of Congo', 'CD', '🇨🇩', 'CDF', true),
('Gabon', 'GA', '🇬🇦', 'XAF', true),
('Chad', 'TD', '🇹🇩', 'XAF', true),
('Niger', 'NE', '🇳🇪', 'XOF', true),
('Burkina Faso', 'BF', '🇧🇫', 'XOF', true),
('Mali', 'ML', '🇲🇱', 'XOF', true),
('Guinea', 'GN', '🇬🇳', 'GNF', true),
('Sierra Leone', 'SL', '🇸🇱', 'SLL', true),
('Liberia', 'LR', '🇱🇷', 'LRD', true),
('Gambia', 'GM', '🇬🇲', 'GMD', true),
('Benin', 'BJ', '🇧🇯', 'XOF', true),
('Togo', 'TG', '🇹🇬', 'XOF', true),
('Burundi', 'BI', '🇧🇮', 'BIF', true),
('Djibouti', 'DJ', '🇩🇯', 'DJF', true),
('Eritrea', 'ER', '🇪🇷', 'ERN', true),
('Somalia', 'SO', '🇸🇴', 'SOS', true),
('South Sudan', 'SS', '🇸🇸', 'SSP', true),
('Lesotho', 'LS', '🇱🇸', 'LSL', true),
('Eswatini', 'SZ', '🇸🇿', 'SZL', true),
('Madagascar', 'MG', '🇲🇬', 'MGA', true),
('Mauritius', 'MU', '🇲🇺', 'MUR', true),
('Seychelles', 'SC', '🇸🇨', 'SCR', true),
('Comoros', 'KM', '🇰🇲', 'KMF', true),
('Mauritania', 'MR', '🇲🇷', 'MRU', true),
('United Kingdom', 'GB', '🇬🇧', 'GBP', true),
('United States', 'US', '🇺🇸', 'USD', true),
('Canada', 'CA', '🇨🇦', 'CAD', true);

