-- ============================================================
-- ELIMUX SEED DATA - PART 2: Countries + Institution Types
-- Run AFTER 01_schema.sql AND 02a_seed_countries_part1.sql
-- ============================================================

INSERT INTO countries (name, iso_code, flag_emoji, currency, is_active) VALUES
('Australia', 'AU', 'AU', 'AUD', true),
('India', 'IN', 'IN', 'INR', true),
('Germany', 'DE', 'DE', 'EUR', true),
('France', 'FR', 'FR', 'EUR', true),
('Netherlands', 'NL', 'NL', 'EUR', true),
('Sweden', 'SE', 'SE', 'SEK', true),
('Norway', 'NO', 'NO', 'NOK', true),
('Denmark', 'DK', 'DK', 'DKK', true),
('Finland', 'FI', 'FI', 'EUR', true),
('Switzerland', 'CH', 'CH', 'CHF', true),
('Austria', 'AT', 'AT', 'EUR', true),
('Belgium', 'BE', 'BE', 'EUR', true),
('Ireland', 'IE', 'IE', 'EUR', true),
('Italy', 'IT', 'IT', 'EUR', true),
('Spain', 'ES', 'ES', 'EUR', true),
('Portugal', 'PT', 'PT', 'EUR', true),
('Poland', 'PL', 'PL', 'PLN', true),
('Czech Republic', 'CZ', 'CZ', 'CZK', true),
('Hungary', 'HU', 'HU', 'HUF', true),
('Romania', 'RO', 'RO', 'RON', true),
('Bulgaria', 'BG', 'BG', 'BGN', true),
('Croatia', 'HR', 'HR', 'EUR', true),
('Greece', 'GR', 'GR', 'EUR', true),
('Turkey', 'TR', 'TR', 'TRY', true),
('Russia', 'RU', 'RU', 'RUB', true),
('Ukraine', 'UA', 'UA', 'UAH', true),
('China', 'CN', 'CN', 'CNY', true),
('Japan', 'JP', 'JP', 'JPY', true),
('South Korea', 'KR', 'KR', 'KRW', true),
('Singapore', 'SG', 'SG', 'SGD', true),
('Malaysia', 'MY', 'MY', 'MYR', true),
('Thailand', 'TH', 'TH', 'THB', true),
('Indonesia', 'ID', 'ID', 'IDR', true),
('Philippines', 'PH', 'PH', 'PHP', true),
('Vietnam', 'VN', 'VN', 'VND', true),
('Brazil', 'BR', 'BR', 'BRL', true),
('Mexico', 'MX', 'MX', 'MXN', true),
('Argentina', 'AR', 'AR', 'ARS', true),
('Chile', 'CL', 'CL', 'CLP', true),
('Colombia', 'CO', 'CO', 'COP', true),
('Peru', 'PE', 'PE', 'PEN', true),
('New Zealand', 'NZ', 'NZ', 'NZD', true),
('United Arab Emirates', 'AE', 'AE', 'AED', true),
('Saudi Arabia', 'SA', 'SA', 'SAR', true),
('Qatar', 'QA', 'QA', 'QAR', true),
('Kuwait', 'KW', 'KW', 'KWD', true),
('Israel', 'IL', 'IL', 'ILS', true),
('Pakistan', 'PK', 'PK', 'PKR', true),
('Bangladesh', 'BD', 'BD', 'BDT', true),
('Sri Lanka', 'LK', 'LK', 'LKR', true),
('Nepal', 'NP', 'NP', 'NPR', true);

INSERT INTO institution_types (name, description, icon, is_active) VALUES
('University', 'Degree-granting institutions offering bachelor, master, and doctoral programs', 'graduation-cap', true),
('College', 'Post-secondary institutions offering diplomas and certificates', 'school', true),
('TVET Institute', 'Technical and Vocational Education and Training institutions', 'wrench', true),
('Polytechnic', 'Institutions focused on technical and applied sciences', 'cog', true),
('Community College', 'Two-year institutions offering associate degrees and vocational training', 'users', true),
('Institute of Technology', 'Specialized institutions focused on science, engineering, and technology', 'microchip', true),
('Business School', 'Institutions specializing in business and management education', 'briefcase', true),
('Medical School', 'Institutions offering medical and health sciences education', 'heart-pulse', true),
('Law School', 'Institutions offering legal education and training', 'scale', true),
('Art School', 'Institutions specializing in fine arts, design, and creative studies', 'palette', true),
('Language School', 'Institutions focused on language learning and cultural studies', 'languages', true),
('Online Institution', 'Fully online or distance learning institutions', 'wifi', true),
('Research Institute', 'Institutions focused on research and postgraduate studies', 'flask', true),
('International School', 'Schools offering international curricula and qualifications', 'globe', true),
('Vocational School', 'Schools offering practical skills and trade training', 'hammer', true)
ON CONFLICT (name) DO NOTHING;

