-- INSERT KENYAN PUBLIC UNIVERSITIES
INSERT INTO institutions (name, slug, type_id, country_id, city, description, website_url, is_verified, is_active, founded_year, student_count) VALUES
('Egerton University', 'egerton-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Njoro', 'Premier agricultural university in Kenya, offering programs in agriculture, engineering, education, and natural resources.', 'https://www.egerton.ac.ke', true, true, 1939, 15000),
('Maseno University', 'maseno-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Maseno', 'Public university near Kisumu offering programs in science, arts, education, and development studies.', 'https://www.maseno.ac.ke', true, true, 1991, 18000),
('Masinde Muliro University of Science and Technology', 'mmust', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Kakamega', 'Science and technology university in Western Kenya, specializing in engineering, agriculture, and health sciences.', 'https://www.mmust.ac.ke', true, true, 1972, 22000),
('South Eastern Kenya University', 'seku', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Kitui', 'University in Ukambani region offering programs in agriculture, education, business, and environmental studies.', 'https://www.seku.ac.ke', true, true, 2008, 12000),
('Karatina University', 'karatina-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Karatina', 'Young public university in Nyeri County focusing on agriculture, business, and education programs.', 'https://www.karu.ac.ke', true, true, 2011, 8000),
('Chuka University', 'chuka-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Chuka', 'Public university in Tharaka Nithi County offering programs in education, business, agriculture, and science.', 'https://www.chuka.ac.ke', true, true, 2004, 10000),
('Laikipia University', 'laikipia-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Nyahururu', 'University in Laikipia County specializing in education, tourism, and natural resource management.', 'https://www.laikipia.ac.ke', true, true, 2013, 7000),
('Meru University of Science and Technology', 'must', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Meru', 'Science and technology university in Meru County, focusing on engineering, agriculture, and ICT.', 'https://www.must.ac.ke', true, true, 2008, 9000),
('Kibabii University', 'kibabii-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Bungoma', 'Public university in Bungoma County offering programs in education, science, and business.', 'https://www.kibu.ac.ke', true, true, 2012, 6000),
('University of Eldoret', 'university-of-eldoret', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Eldoret', 'Public university in Uasin Gishu County specializing in agriculture, education, and health sciences.', 'https://www.uoeld.ac.ke', true, true, 1946, 14000),
('Pwani University', 'pwani-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Kilifi', 'Coastal university in Kilifi County offering programs in marine science, agriculture, and education.', 'https://www.pu.ac.ke', true, true, 2007, 11000),
('Kisii University', 'kisii-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Kisii', 'Public university in Kisii County offering programs in education, business, law, and health sciences.', 'https://www.kisiiuniversity.ac.ke', true, true, 1965, 16000),
('Taita Taveta University', 'ttu', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Voi', 'University in Taita Taveta County focusing on mining, engineering, agriculture, and environmental studies.', 'https://www.ttu.ac.ke', true, true, 2011, 5000),
('Garissa University', 'garissa-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Garissa', 'University in North Eastern Kenya offering programs in education, business, and Islamic studies.', 'https://www.gu.ac.ke', true, true, 1996, 4000),
('Machakos University', 'machakos-university', (SELECT id FROM institution_types WHERE name = 'University'), (SELECT id FROM countries WHERE iso_code = 'KE'), 'Machakos', 'Public university in Machakos County specializing in engineering, technology, and business programs.', 'https://www.mksu.ac.ke', true, true, 1957, 13000);

SELECT 'Kenyan Public Universities' as category, COUNT(*) as count FROM institutions WHERE country_id = (SELECT id FROM countries WHERE iso_code = 'KE') AND type_id = (SELECT id FROM institution_types WHERE name = 'University');
