-- INSERT UK INSTITUTIONS
INSERT INTO institutions (name, slug, type_id, country_id, city, description, website_url, is_verified, is_active, founded_year, student_count) VALUES
('University of Oxford', 'university-of-oxford',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Oxford',
 'World-renowned collegiate research university. Oldest university in the English-speaking world. Famous for humanities, sciences, medicine, and law. Home to Rhodes Scholars from Kenya.',
 'https://www.ox.ac.uk', true, true, 1096, 24000),
('University of Cambridge', 'university-of-cambridge',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Cambridge',
 'Prestigious research university with strong Kenyan alumni network. Excellence in mathematics, physics, engineering, and biological sciences. Many Kenyan leaders studied here.',
 'https://www.cam.ac.uk', true, true, 1209, 21000),
('Imperial College London', 'imperial-college-london',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'London',
 'World-leading science, engineering, and medicine university in London. Strong research partnerships with African institutions. Popular with Kenyan STEM students.',
 'https://www.imperial.ac.uk', true, true, 1907, 19000),
('London School of Economics', 'lse',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'London',
 'Global leader in social sciences, economics, politics, and law. Many Kenyan policymakers and economists are LSE alumni. Strong development studies program.',
 'https://www.lse.ac.uk', true, true, 1895, 12000),
('University of Manchester', 'university-of-manchester',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Manchester',
 'Red brick university with strong engineering, business, and development studies. Active partnerships with Kenyan universities. Large African student community.',
 'https://www.manchester.ac.uk', true, true, 1824, 40000),
('University of Edinburgh', 'university-of-edinburgh',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Edinburgh',
 'Historic Scottish university ranked in global top 20. Strong in medicine, informatics, and international development. Welcoming to Kenyan students.',
 'https://www.ed.ac.uk', true, true, 1582, 35000),
('University of Warwick', 'university-of-warwick',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Coventry',
 'Modern research university with excellent business school and engineering. Strong links with African businesses. Popular for MBA and economics.',
 'https://www.warwick.ac.uk', true, true, 1965, 28000),
('University of Bristol', 'university-of-bristol',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Bristol',
 'Russell Group university with strong engineering, law, and social sciences. Active in African research partnerships. Beautiful city with strong student life.',
 'https://www.bristol.ac.uk', true, true, 1876, 25000),
('University of Nottingham', 'university-of-nottingham',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'Nottingham',
 'Campus university with strong pharmacy, engineering, and agriculture programs. Has a campus in Malaysia. Good scholarships for African students.',
 'https://www.nottingham.ac.uk', true, true, 1881, 33000),
('King''s College London', 'kings-college-london',
 (SELECT id FROM institution_types WHERE name = 'University'),
 (SELECT id FROM countries WHERE iso_code = 'GB'),
 'London',
 'Major London university with world-class medical school, law faculty, and war studies. Strong African studies center. Many Kenyan medical students.',
 'https://www.kcl.ac.uk', true, true, 1829, 31000)
ON CONFLICT (slug) DO NOTHING;

SELECT 'UK Institutions' as category, COUNT(*) as count FROM institutions WHERE country_id = (SELECT id FROM countries WHERE iso_code = 'GB');
